#!/bin/sh

################################
########### MUSIC-DL ###########
################################

# set important variables
CONFIG_DIR="$HOME/.config/music-dl/"
CONFIG_FILE="$CONFIGDIR/settings.conf"
USAGE="Usage: music-dl -t [TARGET URL] -q [SONG/ARTIST/ALBUM]"
HELP="$USAGE
Download music and appropriate metadata.

-t, --target= : specify target URL
-q, --query= : specify search query
-d, --dir= : specify directory for download
-u, --usage : prints usage
-h, --help : prints this message"

API="https://musicbrainz.org/ws/2"
USER_AGENT="music-dl/0.1 ( https://github.com/mrSpooder/music-dl )"

# parse arguments
while [ "$#" -gt 0 ]; do
	case "$1" in
		-u|--usage) echo "$USAGE"; exit 0 ;;
		-h|--help) echo "$HELP"; exit 0 ;;

		-t) URL="$2"; shift 2 ;;
		-q) QUERY="$2"; shift 2 ;;
		-d) DIR="$2"; shift 2 ;;

		--target=*) URL="${1#*=}"; shift 1 ;;
		--query=*) QUERY="${1#*=}"; shift 1 ;;
		--dir=*) DIR="${1#*=}"; shift 1 ;;

		-*) echo "unkown option: $1" >&2; exit 1 ;;
	esac
done

if [[ -z $URL || -z $QUERY ]]; then
	echo "missing target URL and/or search query" >&2;
	echo "$USAGE" >&2;
	exit 1;
fi

